version: "2.4"

services:
  mysql:
    container_name: TodosApp
    image: mysql:5.7.25
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: VIP
    environment:
      MYSQL_DATABASE: 'todosApp'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'

volumes: 
  mysql-volume:
    external: true
    
